apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    tier: monitoring
    app: appdynamics
    version: v1
  name: appd-machineagent
spec:
  template:
    metadata:
      name: appd-machineagent
      labels:
        app: appdynamics
    spec:
      containers:
      - name: appdmachineagent
        image: markjeffery/appd_machine_agent_kubernetes:latest
        command: [ "/start_machine_agent_kubernetes.sh" ]
        volumeMounts:
        - mountPath: /appd_machine_agent
          name: machine-agent
      volumes:
      - name: machine-agent
        hostPath:
          path: /Users/mark.jeffery/Documents/kubernetes/MachineAgent

